language: node_js
node_js: 8.9.1
services:
  - xvfb
before_install:
  - sudo apt-get install libgconf-2-4
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
script:
  - if [ "x${CORE_BRANCH}x" != "xx" ] ; then ./node_modules/.bin/publish_yalc_package .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core ; fi
  - yarn test &&
    yarn test:downstream
env:
  matrix:
    - CORE_BRANCH=
    - CORE_BRANCH=master UPSTREAM_PKGS=@uirouter/core
notifications:
  slack:
    on_success: never
    rooms:
      secure: mthnTDooLMpZxdrwiVOzTwAclJXweZHYmIywUYmGVKV5jztElMZnSXvO+iN4FIu6weQSZ4iXI9S3N3CyX5L2EU7Yykyiixxe/0fxNM/W+X3nFKrWq4a1YrB6KHQHE1vFUx/RUTad6zH8bl1Aw3QLlxMXYCZ/sOlqk78CCXdX+6yr7yZ6UqiCWA6h0F24ZT6W4tProCoc4UuyD+NpRJHEsnOahTz7uEiPybzSSyjNCpo6MlXNXa2b1szTx+4s+1oKRhyVHYIvNY0P6QS15+i/ZXaRp+fFEz0jZNadUyKM3mihVYiiWv4ewSJRmhEyMyiD+fQYm1+ttinrBRuIf60NMaKDeaxer41pC2bOhdNkhrrugVXjjL5hv2u1JyzZP7VAtau77paCBDSXwXFUUoboV87C97Rp92/VkcM7jV0d7PtrltmWYPGiPTIReOnrwlsuvbJkDCj05QkF2sf3lkgShBiMpE/XaH/63YUvB8NuQyR5awPlR6XamnAW52uH9iVKx5Lg6Np5hCu2WxMME/qf5K2IfCjaHcLU91lMT/8eo+o6bYgrJs3BXQN7YFkmmZeYmbVXO1o83L0Xlcgf2WWy3nzIRI/v1xyIrGoIFBs/cIWAKB/4Am5hRYzUel9vgInTq//Se0mKMQgbNLkGaFHw4mI220Qz8O0fhs5bUdDfQRs=
sudo: false
git:
  depth: 3
cache:
  directories:
    - node_modules
    - '.downstream_cache'
